dscrm_service/dscrm_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('orders/', include('orders.urls')),
    path('clients/', include('clients.urls')),
]

dscrm_service/orders/urls.py
from django.urls import path

from .views import OrderList, create_order, ShowOrder, OrderUpdate, OrderDelete

urlpatterns = [
    path('', OrderList.as_view(), name='orders'),
    path('create/', create_order, name='order_create'),
    path('<int:pk>/', ShowOrder.as_view(), name='order'),
    path('<int:pk>/update', OrderUpdate.as_view(), name='order-update'),
    path('<int:pk>/delete', OrderDelete.as_view(), name='order-delete')
]

dscrm_service/users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import UserView, signup

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup')
]

dscrm_service/orders/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse

from clients.models import Client
from devices.models import Device


class Order(models.Model):
    """Класс для создания заявки"""

    class Meta:
        db_table = "orders"
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"

    statuses = (("open", "открыта"),
                ("closed", "закрыта"),
                ("in progress", "в работе"),
                ("need info", "нужна информация"))

    client = models.ForeignKey(Client, on_delete=models.RESTRICT, verbose_name="Клиент")
    device = models.ForeignKey(Device, verbose_name="Устройство", on_delete=models.RESTRICT)
    order_description = models.CharField(verbose_name="Неисправность")
    created_dt = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    last_updated_dt = models.DateTimeField(verbose_name="Последнее изменение", blank=True, null=True)
    order_status = models.TextField(verbose_name="Статус заказа", choices=statuses)
    price = models.CharField(verbose_name='Ориентировочная стоимость', blank=True, null=True)
    services = models.ManyToManyField('services.Service', through='services.ServiceItem', verbose_name="Услуга",
                                      blank=True)

    def __str__(self):
        return f"Заявка №{self.id} для {self.device}"

    def save(self, *args, **kwargs):
        self.last_updated_dt = datetime.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('order', kwargs={'pk': self.pk})

dscrm_service/orders/forms.py
from django import forms

from devices.models import Group, Brand, Model
from orders.models import Order


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('client', 'device', 'order_description', 'price', 'order_status')
        widgets = {
            'order_description': forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'type': 'text'}),
        }


class OrderForm(forms.Form):
    client_name = forms.CharField(label='Имя клиента', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text'}))
    client_phone = forms.CharField(label='Номер телефона', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text'}))
    device_group = forms.ModelChoiceField(empty_label='Выберите группу', label='Группа', queryset=Group.objects.all(),
                                          widget=forms.Select(
                                              attrs={'class': 'form-control'}))
    device_brand = forms.ModelChoiceField(empty_label='Выберите бренд', label='Бренд', queryset=Brand.objects.all(),
                                          widget=forms.Select(
                                              attrs={'class': 'form-control'}))
    device_model = forms.ModelChoiceField(empty_label='Выберите Модель', label='Модель', queryset=Model.objects.all(),
                                          widget=forms.Select(
                                              attrs={'class': 'form-control'}))
    device_serial = forms.CharField(label='Серийный номер', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text'}))
    order_description = forms.CharField(label='Неисправность', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text'}))
    price = forms.CharField(label='Ориентировочная цена', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text'}))

dscrm_service/orders/views.py
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import OrderForm, OrderUpdateForm
from .models import Order, Client, Device


logger = logging.getLogger('main')

class OrderList(ListView):
    model = Order
    template_name = 'orders/orders.html'
    context_object_name = 'orders'
    extra_context = {'title': 'Таблица заявок'}


class ShowOrder(UpdateView):
    model = Order
    template_name = 'orders/order_info.html'
    context_object_name = 'order'
    extra_context = {'title': 'Просмотр заказа'}
    fields = ['services']
    success_url = reverse_lazy('orders')


class CreateOrder(CreateView):
    form_class = OrderForm
    template_name = 'orders/create_order.html'
    extra_context = {'title': 'Создание Заявки'}
    success_url = reverse_lazy('orders')


def create_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            client_name = form.cleaned_data['client_name']
            client_phone = form.cleaned_data['client_phone']
            client = Client.objects.filter(client_phone=client_phone).first()
            client = client or Client.objects.create(client_name=client_name, client_phone=client_phone)
            device_group = form.cleaned_data['device_group']
            device_brand = form.cleaned_data['device_brand']
            device_model = form.cleaned_data['device_model']
            device_serial = form.cleaned_data['device_serial']
            device = Device.objects.create(group=device_group, brand=device_brand, model=device_model,
                                           serial_number=device_serial)
            order_description = form.cleaned_data['order_description']
            price = form.cleaned_data['price']
            Order.objects.create(client=client, device=device, order_description=order_description, order_status='open',
                                 price=price)
            logger.info(f'Order for client: "{client_name}" have been created')
            return HttpResponseRedirect('/orders/')
    else:
        form = OrderForm
    return render(request, 'orders/create_order.html', {'form': form})


class OrderUpdate(UpdateView):
    model = Order
    template_name = 'orders/order_update.html'
    extra_context = {'title': 'Просмотр и редактирование заказа'}
    form_class = OrderUpdateForm
    # fields = ['client', 'device', 'order_description', 'order_status', 'price', 'services']
    success_url = reverse_lazy('orders')


class OrderDelete(DeleteView):
    model = Order
    template_name = 'orders/order_delete.html'
    success_url = reverse_lazy('orders')

dscrm_service/orders/templates/orders/base.html
<!doctype html>
<html lang="en" class="semi-dark">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--favicon-->
    <link rel="icon" href="{% static 'orders/images/favicon-32x32.png' %}" type="image/png"/>
    <!--plugins-->

    <link href="{% static 'orders/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet"/>

    <!-- loader-->

    <!-- Bootstrap CSS -->
    <link href="{% static 'orders/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'orders/css/bootstrap-extended.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link href="{% static 'orders/css/app.css' %}" rel="stylesheet">
    <link href="{% static 'orders/css/icons.css' %}" rel="stylesheet">
    <!-- Theme Style CSS -->
    <link rel="stylesheet" href="{% static 'orders/css/dark-theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'orders/css/semi-dark.css' %}"/>
    <link rel="stylesheet" href="{% static 'orders/css/header-colors.css' %}"/>
    <title>{{title}}</title>
</head>

<body>
<!--wrapper-->
<div class="wrapper">
    <!--sidebar wrapper -->
    <div class="sidebar-wrapper" data-simplebar="true">
        <div class="sidebar-header">
            <div>
                <img src="{% static 'orders/images/logo-icon.png' %}" class="logo-icon" alt="logo icon">
            </div>
            <div>
                <h4 class="logo-text">DS CRM</h4>
            </div>
            <div class="toggle-icon ms-auto"><i class='bx bx-arrow-back'></i>
            </div>
        </div>
        <!--navigation-->
        <ul class="metismenu" id="menu">
            <li>
                <a href="javascript:;" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-home-alt'></i>
                    </div>
                    <div class="menu-title">Обзор</div>
                </a>
            </li>
            <li>
                <a href="{% url 'orders'%}" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-bookmark-heart'></i>
                    </div>
                    <div class="menu-title">Заказы</div>
                </a>
            </li>
			 <li>
                <a href="javascript:;" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-cart'></i>
                    </div>
                    <div class="menu-title">Продажи</div>
                </a>
            </li>
			 <li>
                <a href="javascript:;" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-diamond'></i>
                    </div>
                    <div class="menu-title">Финансы</div>
                </a>
            </li>
			 <li>
                <a href="javascript:;" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-video-recording'></i>
                    </div>
                    <div class="menu-title">Устройства</div>
                </a>
            </li>
			 <li>
                <a href="{% url 'clients' %}" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-user-circle'></i>
                    </div>
                    <div class="menu-title">Клиенты</div>
                </a>
            </li>

        </ul>
        <!--end navigation-->
    </div>
    <!--end sidebar wrapper -->
    <!--start header -->
    <header>
        <div class="topbar d-flex align-items-center">
            <nav class="navbar navbar-expand gap-3">
                <div class="mobile-toggle-menu"><i class='bx bx-menu'></i>
                </div>
                <div class="position-relative search-bar d-lg-block d-none" data-bs-toggle="modal"
                     data-bs-target="#SearchModal">
                    <input class="form-control px-5" disabled type="search" placeholder="Search">
                    <span class="position-absolute top-50 search-show ms-3 translate-middle-y start-0 top-50 fs-5"><i
                            class='bx bx-search'></i></span>
                </div>
                <div class="top-menu ms-auto">
                    <ul class="navbar-nav align-items-center gap-1">
                        <li class="nav-item mobile-search-icon d-flex d-lg-none" data-bs-toggle="modal"
                            data-bs-target="#SearchModal">
                            <a class="nav-link" href="javascript:;"><i class='bx bx-search'></i>
                            </a>
                        </li>

                        <li class="nav-item dark-mode d-none d-sm-flex">
                            <a class="nav-link dark-mode-icon" href="javascript:;"><i class='bx bx-moon'></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="user-box dropdown px-3">
                    <a class="d-flex align-items-center nav-link dropdown-toggle gap-3 dropdown-toggle-nocaret"
                       href="{% url 'users:profile' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'orders/images/avatars/avatar-1.png' %}" class="user-img" alt="user avatar">
                        <div class="user-info">
                            <p class="user-name mb-0">{{user.name}}</p>
                            <p class="designattion mb-0">{{user.email}}</p>
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item d-flex align-items-center" href="{% url 'users:profile' %}"><i
                                class="bx bx-user fs-5"></i><span>Profile</span></a>
                        </li>
                        <li><a class="dropdown-item d-flex align-items-center" href="javascript:;"><i
                                class="bx bx-cog fs-5"></i><span>Settings</span></a>
                        </li>
                        <li>
                            <div class="dropdown-divider mb-0"></div>
                        </li>
                        <li><a class="dropdown-item d-flex align-items-center" href="{% url 'users:logout' %}"><i
                                class="bx bx-log-out-circle"></i><span>Logout</span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--end header -->
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">
            <!--breadcrumb-->

            <!--end breadcrumb-->
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!--end page wrapper -->
    <!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
    <!--End Back To Top Button-->
    <footer class="page-footer">
        <p class="mb-0">Copyright © 2023. All right reserved.</p>
    </footer>
</div>
<!--end wrapper-->

<!-- Bootstrap JS -->
<script src="{% static 'orders/js/bootstrap.bundle.min.js' %}"></script>
<!--plugins-->

<script src="{% static 'orders/js/jquery.min.js' %}"></script>
<script src="{% static 'orders/plugins/simplebar/js/simplebar.min.js' %}"></script>
<script src="{% static 'orders/plugins/metismenu/js/metisMenu.min.js' %}"></script>
<script src="{% static 'orders/plugins/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>
<script src="{% static 'orders/plugins/bs-stepper/js/bs-stepper.min.js' %}"></script>
<script src="{% static 'orders/plugins/bs-stepper/js/main.js' %}"></script>
<!--app JS-->
<script src="{% static 'orders/js/app.js' %}"></script>
</body>

</html>

dscrm_service/orders/templates/orders/create_order.html
<!DOCTYPE html>
{% extends 'orders/base.html' %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
{% block content %}
<div class="col-xl-6 mx-auto">
    <div class="card">
        <div class="card-body p-4">
            <h5 class="mb-4">Создание нового заказа</h5>
            <form class="row g-3" method="post">
                <div> {{form.not_field_errors}}</div>
                {% csrf_token %}
                {% for f in form %}
                <div class="col-md-12">
                    <label for="input1" class="form-label">{{f.label}}</label>
                    {{f}}
                    <div>{{f.errors}}</div>
                </div>
                {% endfor %}
                <div class="col-md-12">
                    <div class="d-md-flex d-grid align-items-center gap-3">
                        <button type="submit" class="btn btn-primary px-4">Submit</button>
                        <button type="reset" class="btn btn-light px-4">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

dscrm_service/orders/templates/orders/order_info.html
<!DOCTYPE html>
{% extends 'orders/base.html' %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>

{% block content %}

<div class="col-xl-6 mx-auto">
    <div class="card">
        <div class="card-body p-4">
            <h5 class="mb-4">Создание нового заказа</h5>
            <form class="row g-3" method="post">
                <div> {{form.not_field_errors}}</div>
                {% csrf_token %}
                {% for f in form %}
                <div class="col-md-12">
                    <label for="input1" class="form-label">{{f.label}}</label>
                    {{f}}
                    <div>{{f.errors}}</div>
                </div>
                {% endfor %}
                <div class="col-md-12">
                    <div class="d-md-flex d-grid align-items-center gap-3">
                        <button type="submit" class="btn btn-primary px-4">Submit</button>
                        <button type="reset" class="btn btn-light px-4">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



<p>{{order.created_dt}}</p>
<p>{{order.client}}</p>
<p>{{order.device}}</p>
<p>{{order.order_description}}</p>
<p>{{order.order_status}}</p>
<p>{{order.price}}</p>

{% endblock %}
</body>
</html>

dscrm_service/orders/templates/orders/orders.html
<!DOCTYPE html>
{% extends 'orders/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
{% block content %}
 <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="breadcrumb-title pe-3">eCommerce</div>
                <div class="ps-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0 p-0">
                            <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Заказы</li>
                        </ol>
                    </nav>
                </div>
            </div>
	<div class="card">
					<div class="card-body">
						<div class="d-lg-flex align-items-center mb-4 gap-3">
							<div class="position-relative">
								<input type="text" class="form-control ps-5 radius-30" placeholder="Search Order"> <span class="position-absolute top-50 product-show translate-middle-y"><i class="bx bx-search"></i></span>
							</div>
						  <div class="ms-auto"><a href="{% url 'order_create' %}" class="btn btn-primary radius-30 mt-2 mt-lg-0"><i class="bx bxs-plus-square"></i>Add New Order</a></div>
						</div>
						<div class="table-responsive">
							<table class="table mb-0">
								<thead class="table-light">
									<tr>
										<th>№</th>
										<th>Клиент</th>
										<th>Статус</th>
										<th>Устройство</th>
                                        <th>Неисправность</th>
										<th>Дата</th>
										<th>Действия</th>
									</tr>
								</thead>
								<tbody>
                                {% for order in orders %}
									<tr>
										<td>
											<div class="d-flex align-items-center">
												<div>
													<input class="form-check-input me-3" type="checkbox" value="" aria-label="...">
												</div>
												<div class="ms-2">
													<h6 class="mb-0 font-14"><a href="{{order.get_absolute_url}}">#{{order.pk}}</a></h6>
												</div>
											</div>
										</td>
										<td>{{order.client}}</td>
										{% if order.order_status == 'open' %}
										<td><div class="badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{order.order_status}}</div></td>
										{% elif order.order_status == 'in progress' %}
										<td><div class="badge rounded-pill text-info bg-light-info p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{order.order_status}}</div></td>
										{% elif order.order_status == 'need info' %}
										<td><div class="badge rounded-pill text-warning bg-light-warning p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{order.order_status}}</div></td>
										{% elif order.order_status == 'closed' %}
										<td><div class="badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{order.order_status}}</div></td>
										{% endif %}
                                        <td>{{order.device}}</td>
                                        <td>{{order.order_description}}</td>
										<td>{{order.created_dt}}</td>
										<td>
											<div class="d-flex order-actions">
												<a href="{% url 'order-update' order.id %}" class=""><i class='bx bxs-edit'></i></a>
												<a href="{% url 'order-delete' order.id %}" class="ms-3"><i class='bx bxs-trash'></i></a>
											</div>
										</td>
									</tr>
                                    {% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
{% endblock %}
</body>
</html>